version: '3.3'
services:
  docker-lineage-cicd:
    environment:
      - BRANCH_NAME=lineage-18.1
      - DEVICE_LIST=lavender
      - SIGN_BUILDS=true
      - PARALLEL_JOBS=8
      - TZ=Europe/Madrid
      - DELETE_OLD_ZIPS=1
      - DELETE_OLD_LOGS=1
      - CLEAN_OUTDIR=true
      - CLEAN_AFTER_BUILD=true
    volumes:
      - lineage:/srv/src
      - ~/dev/repo/lineageos/zips:/srv/zips
      - ~/dev/repo/lineageos/logs:/srv/logs
      - cache:/srv/ccache
      - ~/dev/repo/lineageos/keys:/srv/keys
    image: lineageos4microg/docker-lineage-cicd

volumes:
  cache:
  lineage:
